### ISSUE TITLE
Website Ideas

### ISSUE THREAD

**Issue by Murthyan97** [MiragonMx/aurealm_web#1]
Essentials Prio: 

- [ ] Blog Page
- [ ] Startseite
- [ ] Funktionierende Website lol

Essentials weniger Prio:

- [ ] Seite für Regelwerk, Excel Sheets etc.
- [ ] Color Schemes
- [ ] Link, QR-Code zu Insta/Buch, etc.

Nice 2 have:

- [ ] Charakterseite (Bild, Charakterbeschreibung)
- [ ] Maps
- [ ] Glossar
- [ ] Links im Blog zum Glossar

Advanced Nice 2 have:

- [ ] Charakterseite (Skilltree Kampffähigkeiten und Attributswerte, Level zum durchklicken)
- [ ] Map mit Crosslinks zum Glossar
- [ ] Würfelanimation auf Startseite mit Farb Schemes und Websitereiter
- [ ] Würfelgenerator für W4, W6, W8, W10, W12, W20

**Comment by MiragonMx** [comment]
included as roadmap in readme, added multiple new issues tracking the individual tasks
