### ISSUE TITLE
Regelseiten (inkl. Formeln)

### ISSUE THREAD

**Issue by MiragonMx** [MiragonMx/aurealm_web#182]
I've tried to "activate" typesetting for formulas and the overall rule-system content part. This is done in the branch `branch-rules-math` which should be the base for a pull request introducing a first rule system post. Here, a German and English testpage are added (should have a thumbnail as well for consistency in website design).

However, the easiest way to include LaTeX-esque typesetting with MathJaX (which should be sufficient) somehow does not fully work yet. Some problems I face(d):
- not all math delimiters 'work', currently the `$$....$$` version seems fine, others, including inline math, don't
- at least in part that is probably because of missing support by the Hugo build system. The typesetting inclusion I added works only with Hugo version >= 0.122.0 - I run a lower version locally and the automatic version with the cloudflare hosting is also just 0.118.2 or something. 
- the summary shown on the post cards is a bit jumbled.

I have already set the build version with our host to 0.122, in a first test that didn't make a difference though. This is done by setting environment variables in the dashboard and I'm not sure, if I did this correctly. I will look into that again in the future.

@Murthyan97 for now, as at least some formatting does work I would suggest that you
- try to add rule system pages with only Displaystyle equations/formulas delimited by `$$`
- add a manual summary in the frontmatter as you do with the blogs without any math or similar that needs the TeX formatting

**Comment by MiragonMx** [comment]
https://gohugo.io/content-management/mathematics/

This is the main page, in which the 'hugo-side' of things is shown. It should be straightforward and also it points to the MathJax and KaTeX pages, should you want to look in the details there and weigh in for one or the other...

**Comment by Murthyan97** [comment]
I would prefer a rulepage without single "rule posts" with thumbnail etc. Instead I was thinking about a design similar to the "about us"-section. For uploading content like PDFs i found a suitable solution. I created a "Buy me a coffee" account, which is similar to patreon but without the need to upload content regularly. Furthermore i can relate way more to coffee and the icon is cute.

**Comment by MiragonMx** [comment]
Alright, that should be easy enough. Do you just want to dum everything there at once? You should then probably think about sections/subsections/subsubsections (increasing amount of `#` at the start of line in md) and I'll look into how to create a Linklist/ToC at the top of the page when I have some time :)

**Comment by MiragonMx** [comment]
BMaC seems reasonable enough as well 👍

**Comment by Murthyan97** [comment]
Mach Urlaub du spacken

**Comment by Murthyan97** [comment]
TOC and link list sounds like a neat idea. I was wondering if its possible to include icons (like the spotify/insta/github icons on the bottom of each page) into a text as well, bc i would love having small coffee cubs in the text whenever referring to the BMaC site

**Comment by Murthyan97** [comment]
To do (deadline 28.05.24):
- [ ] changing header from "Regeln" & "Rules" to "Regelwerk" & "Rulebook"
- [ ] Links zwischen einzelnen Karten (Verweis auf die Karte "Kampfsystem bspw.)
- [ ] Tabellen zentrieren und "Begrenzungen" anzeigen
- [ ] Matheformelnm in Tabellen
- [ ] Kartenreihenfolge

**Comment by MiragonMx** [comment]
> To do (deadline 28.05.24):
> 
>     * [x]  changing header from "Regeln" & "Rules" to "Regelwerk" & "Rulebook"
done in 697a28c
>     * [x]  Links zwischen einzelnen Karten (Verweis auf die Karte "Kampfsystem bspw.)
done in 7477737
>     * [ ]  Tabellen zentrieren und "Begrenzungen" anzeigen
- sort of halfway done in 126f109, responsiveness regarding light/dark mode still needed
>     * [ ]  Matheformelnm in Tabellen
- not done, also probably the problem still for inline math (e.g. in character creation)
>     * [x]  Kartenreihenfolge
done in 70bad66

- Styling: golden Sub-headings (differ from Links by underlines)
done in 8f1b4db

No idea if/when I will get to that in the near future - I'll try but I'm already swamped and have now already spent more than an hour more than planned on those changes...

**Comment by MiragonMx** [comment]
> * [ ]  Tabellen zentrieren und "Begrenzungen" anzeigen

>     * sort of halfway done in [126f109](https://github.com/MiragonMx/aurealm_web/commit/126f1099be628a6d47bd7eb40c957951ae9a0464), responsiveness regarding light/dark mode still needed
fixed in c74c072 (now light/dark table depending on theme)

**Comment by MiragonMx** [comment]
I rebased on main to get Regelwerk branch up-to-date, but that changed the commit hashes...
> To do (deadline 28.05.24):
> 
>     * [x]  changing header from "Regeln" & "Rules" to "Regelwerk" & "Rulebook"
done in 5fcc5aafb668219b7f0739ba85b6dc966027f27c
>     * [x]  Links zwischen einzelnen Karten (Verweis auf die Karte "Kampfsystem bspw.)
done in 679f8938b91403d73355467c9f3c56e1a5c36b5a
>     * [x]  Tabellen zentrieren und "Begrenzungen" anzeigen
done in 47d80120a716d2201582529a4852ab30eb5258c4 & fc85fe621c36168c4c2f8670a697e793bf632392 & 751608da41d77f2c1a2042599b8b6dfb0330715f
>     * [x]  Matheformelnm in Tabellen
done finally in 4b31d790cdb77a3467a21f7b70fdd1a5323d2968 (intermediate tries in different commits, see [history](https://github.com/MiragonMx/aurealm_web/commits/Regelwerk/))
>     * [x]  Kartenreihenfolge
done in e3105fe591eb9545d85fce14e87c120882ebf172

- Styling: golden/red (dark/light) Sub-headings (differ from Links by underlines)
done in 4dbb1c3153c86d4e9b670c214f3b1e1266db56de & 3efe2d833cbb12132e89c06ed7b1b90232722e71 & 2373148fe762e890a5d407589afc04799a2d16c1 (intermediate tries as well)
- Note: use subheadings at most inside a post (`##`), as the top level heading (`#`) is reserved for the page title (from the front matter) - see also 2b0d0d7dec433f8c27431346a81d81d5fd1bce4d
- Note: dont use `~` in math mode for spaces, use `\ ` to not mess with crossout-styling by markdown - see also 1cbf52e5251bb4936288b884544c3298ecc4a3c1
- Added very short top-level description of rules list pages (also for SEO) - see 4c939d7cb7119cead92f96fc2d62e24f7be93d54
- Correct folder paths for translation to work - see 6ef39c9956ad851ba2ea7e8579748bf9149eac40
- Icons now also uploaded in repo (feaa829a162a703e5dd090d4ba816e3b390b0e91)

Should cover basically everything talked about @Murthyan97
